server:
  port: ${PORT:5432}
logging:
  level:
    # Logga l'avvio e la configurazione di Hibernate
    org.hibernate.boot: DEBUG
    org.hibernate.boot.spi: DEBUG

    # Logga la gestione dell'EntityManager e della persistenza di Spring
    org.springframework.orm.jpa: DEBUG

    # Logga le query SQL e il binding dei parametri (utile dopo il fix del deploy)
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE # Per Hibernate 6 / Spring Boot 3
    # org.hibernate.type.descriptor.sql: TRACE # Se usi Hibernate 5 o precedenti
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://dpg-d5n1u6lactks73c6molg-a.frankfurt-postgres.render.com:5432/cleaning_io2r}
    username: ${DB_USERNAME:cleaning_io2r_user}
    password: ${DB_PASSWORD:CHUK8gF2Kxmg1mnl0u63gVOZJFB1WaQA}

  jpa:
    properties:
      hibernate:
        ddl-auto: validate           # Controlla che le tabelle/esistano, non le modifica
        show_sql: true               # Mostra tutte le query generate da Hibernate
        format_sql: true             # Formatta le query per leggibilit√†